alias df='df -h'
alias systemLog='less +F /var/log/system.log'
#alias xflux='$HOME/Downloads/software/xflux -l 23.2 -g 113.2 -k 4600'
alias cp='cp -iv'
alias mv='mv -vi'
alias mkdir="mkdir -p"
alias ln='ln -v'
alias ...='../..'
alias roll='$HOME/Documents/tools/roll.py'
# alias goagent='python $HOME/Downloads/goagent/local/proxy.py'
alias editHosts='sudo mvim /etc/hosts'
alias you-get-proxy='proxychains4 python3 $HOME/Documents/development/repos/you-get/you-get'
alias you-get='python3 $HOME/Documents/development/repos/you-get/you-get'
#alias drbox='$HOME/Documents/tools/Dropbox-Uploader/dropbox_uploader.sh'
#alias suspend.lock='$HOME/Dropbox/dotfiles/suspend_script.sh'
#alias D='cd /media/niko/PersonalData/'
#alias E='cd /media/niko/Music'
#alias F='cd /media/niko/Movie'
#alias G='cd /media/niko/Storage'
alias t='$HOME/Documents/tools/tTrans.py'
alias ip.search='$HOME/Documents/tools/ip_search.py'
alias ping='ping -c 10'
alias gen.psd='$HOME/Documents/tools/generate_password.py'
#alias remove_old_kernel='$HOME/Dropbox/dotfiles/remove_old_kernel.sh'
alias h='history'
alias editAlias='vim /Users/niko/Documents/dotfiles/DotFiles/ShellAlias.sh'
alias editPac='vim $HOME/.ShadowsocksX/user-rule.txt'
alias tt='tmux attach'
alias l='ls -alh'
alias luTorrent="$HOME/Documents/development/repos/LuTorrent/lutorrent.py"
alias getMyIP="curl -k --socks5-hostname localhost:1080 ipinfo.io"
alias rentCalculatior="python $HOME/Documents/tools/rent_calculator.py"
alias fetchMail="$HOME/Documents/tools/mailinator.py"
alias bilibili="/Users/niko/Documents/development/repos/biligrab-danmaku2ass/bilidan.py"
alias WoW="cat $HOME/Dropbox/PDS/WOWO.txt"
alias baiduPan="$HOME/Documents/development/repos/iScript/pan.baidu.com.py"
alias rsync="rsync -avP"
alias du="du -sh"


# Mac only
alias openFTPServer="sudo launchctl load -w /System/Library/LaunchDaemons/ftp.plist"
alias closeFTPServer="sudo launchctl unload -w /System/Library/LaunchDaemons/ftp.plist"
#alias openWinDisk='open /Volumes/win7/Users/niko/Downloads'
alias reloadSound='sudo kextunload /System/Library/Extensions/AppleHDA.kext && sudo kextload /System/Library/Extensions/AppleHDA.kext'
# alias flushDNS="sudo killall -HUP mDNSResponder" ## 10.9
alias flushDNS="sudo discoveryutil udnsflushcaches" ## 10.10
alias brewUpdateCleanup="brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup"
alias mountEFI="mkdir /Volumes/EFI && sudo mount -t msdos /dev/disk0s1 /Volumes/EFI"
alias wifi='networksetup -setairportnetwork en0 ccr629@fast 013257489@h'
alias vim="mvim"

