#!/bin/bash

## Created By Aditya Shakya

# MENU="$(rofi -sep "|" -dmenu -i -p 'System' -width 12 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 <<< " Lock| Logout| Suspend| Reboot| Shutdown")"
MENU="$(rofi -sep "|" -dmenu -i -p 'System' <<< " Lock| Logout| Suspend| Reboot| Shutdown")"
            case "$MENU" in
                *Lock) betterlockscreen -l ;;
                *Logout) i3-msg exit;;
                *Suspend) systemctl suspend;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
